### ISSUE TITLE
Installing the parser

### ISSUE THREAD

**Issue by RealHabix** [Analogy-LogViewer/Analogy.LogViewer.Serilog#2]
How do I get it to show up in Analogy? I compiled it and moved the .dll to same folder as analogy without any luck.

**Comment by LiorBanai** [comment]
Hi,
Currently it is a preliminary parser that does not support all serlilog outputs formats .I you have a specific log file example/format you are using you can send it to me at LiorBanai@gmail.com and I'll match the logic for your logs  and send you detailed instructions  how to use it :)

**Comment by LiorBanai** [comment]
Still relevant? if not I'll close this issue.

**Comment by LiorBanai** [comment]
btw, if your logs are plain text, I'm working on generic plain text (and later json) to parse any logs

**Comment by LiorBanai** [comment]
you might find this useful if you are using plaint text output:
https://github.com/Analogy-LogViewer/Analogy.LogViewer.PlainTextParser

**Comment by LiorBanai** [comment]
if you are using [compact formatting](https://github.com/serilog/serilog-formatting-compact) then I have added support for this format for now.

**Comment by LiorBanai** [comment]
you can now download a complete Package that include the Serilog Parser from:
https://github.com/Analogy-LogViewer/Analogy.LogViewer/releases

**Comment by LiorBanai** [comment]
It's now support both clef format and regular expression so you might want to give it a try
