### ISSUE TITLE
Error reading clef file opened by Serilog File sink

### ISSUE THREAD

**Issue by mvenditto** [Analogy-LogViewer/Analogy.LogViewer.Serilog#33]
Hi,

Trying to open a clef log file that's actually opened by Serilog.Sinks.File (with **shared** flag set) causes: 
```
Error reading file XXX: Error: The process cannot access the file 'XXX' because it is being used by another process.
```

The problem seems to be ClefParser using`File.OpenText` that cannot access the file when it is open for writing by another process. 

Setting the approriate flags while opening the file solves the problem.
I've tried the following change and it does the trick :

```cs
using (var clef = File.OpenText(fileName))
```

to

```csharp
using (var fileStream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
using (var clef = new StreamReader(fileStream, encoding: Encoding.UTF8))
```
Could this be a reasonable fix?

Thanks

**Comment by LiorBanai** [comment]
Hi, you are correct :)
I had the same issue with other parser (Nlog), fixed there  and forgot to make the same fix here.
would you like to submit a PR (since you already check the issue)  or do you want me to fix it?

**Comment by mvenditto** [comment]
Sure, gonna submit the pr soon. Should the same fix be applied to the JsonParser also?

**Comment by LiorBanai** [comment]
yeah, it is also relevant to that parser.
