### ISSUE TITLE
Duplicated/Extra columns with the dynamic columns feature?

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.LogViewer.Serilog#44]
Hi,

I had a quick test with the dynamic columns feature in the latest release, and when fed with

```
{"@t":"2020-06-26T14:21:34.7233612Z","@mt":"x","@l":"Error", "MachineName":"Test", "SourceContext":"Program"}
{"@t":"2020-06-30T18:49:18.2133753Z","@mt":"y", "CustomProperty":"Custom Value"}
{"@t":"2020-06-30T18:49:18.2342331Z","@mt":"z","@l":"Error", "ThreadId":42, "ProcessId":876}
{"@t":"2020-06-30T18:49:18.2342331Z","@mt":"z","@l":"Error", "User":"Me", "CustomProperty2":"Another Value"}
```

I got the following columns in the UI:

![image](https://user-images.githubusercontent.com/1178570/86543145-d9591800-bf13-11ea-90db-2e8b48f9671a.png)

So, It's displaying the custom property columns, but also has extra 'ThreadId' and 'ProcessId' columns which perhaps aren't needed? (and are blank in any case).
Also not sure if it needs to have SourceContext as an explicit column, if that value is already being used to populate the Source column?

Possibly the collection of custom properties could be filtered to remove the ones used to populate the built-in/default columns?

**Comment by LiorBanai** [comment]
Thanks for testing this one. I was not sure how mature the feature was before committing  it :)
saw it too after releasing. I plan to add ignore list option in the User Settings UI and fix the duplication columns like you wrote in the last line :)
