### ISSUE TITLE
Support for reading compressed files?

### ISSUE THREAD

**Issue by Numpsy** [Analogy-LogViewer/Analogy.LogViewer.Serilog#45]
Hi,

I'm not sure if this idea is in scope for the library, or indeed just for Serilog bit (none-Serilog specific), but:

I recently had a look at some Serilog add-ons that compress the log files at various points (e.g. https://github.com/cocowalla/serilog-sinks-file-gzip, https://github.com/cocowalla/serilog-sinks-file-archive), and it came to mind that it could possibly be useful to be able to read the .gz compressed log files without having to unpack them first?

Doing so could possibly be as simple as wrapping the FileStreams in GzipStreams before reading the contents, though I do have a slight recollection that the .NET 4.7 version of GZipStream would only read the first chunk of the file when given a .gz file that contains multiple pieces (which was fixed in the .NET Core version). I haven't tested it though, this is just a thought at the moment.

Any thoughts?

**Comment by LiorBanai** [comment]
Very interesting and worth checking. Especially for users the are using compressed files daily. The task of unpacking could get very tiresome after some time.

**Comment by LiorBanai** [comment]
One option is to just unzip the content into temp folder, read all files and then delete them.
Another option is to read directly the file stream and process it in memory. 

It could be at the library level or the  extension. Need to think about it a little :)

**Comment by LiorBanai** [comment]
@Numpsy  do you have an example gz file by any chance?  I have added small implementation but don't have nominal archive to test it on.

**Comment by Numpsy** [comment]
This is a trivial clef/gz file that I created with a test app and the Serilog File and File.GZip sinks:

[SerilogTest.Clef.gz](https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog/files/4944574/SerilogTest.Clef.gz)

(I don't think there should be any difference to a plain .clef file compressed to a .gz using gzip/7-zip etc though)

**Comment by LiorBanai** [comment]
Thanks :)
so I have added in memory parsing.

![image](https://user-images.githubusercontent.com/36262995/87885199-bbfc7180-ca1c-11ea-8590-19cedc525f77.png)

in case the data provider does not support compressed file I'm falling back to local unziping (and adding to the file open dialog the extensions):
![image](https://user-images.githubusercontent.com/36262995/87885172-8ce60000-ca1c-11ea-8f94-73245146cf67.png)

**Comment by Numpsy** [comment]
Thanks, looks good.
