### ISSUE TITLE
Can't parse dictionary that contains an empty key

### ISSUE THREAD

**Issue by JonasToedter** [Analogy-LogViewer/Analogy.LogViewer.Serilog#499]
Log messages that contain a dictionary with an empty key ("") cannot be parsed:
`Error reading file C:\log.clef: Error: Property name must not be empty or whitespace. (Parameter 'name')`

Yet Serilog is able to serialize dictionaries with empty keys, and the [ECMA-404 JSON specification](https://www.ecma-international.org/publications-and-standards/standards/ecma-404/) also allows empty strings as names:
> The JSON syntax does not impose any restrictions on
> the strings used as names, ...

The problem arises from the CompactJsonFormatParser using Serilog.Events.LogEvent as an intermediary to create analogy log messages from the filestream. While reading from the deserialized JObject, instances of Serilog.Events.LogEventProperty are created from the properties of the JObject. The constructor of Serilog.Events.LogEventProperty then throws an exception if the passed property name is null or whitespace.

While replacing empty or whitespace names with a non-empty and non-whitespace name like "\<empty\>" would suffice, it should probably be considered to handle those properties differently, for example through a custom implementation of LogEventProperty that allows names to be empty or whitespace.

**Comment by LiorBanai** [comment]
Hi @JonasToedter , very interesting edge case.  Ideally  there shouldn't be any modification of the text.
I'll check this.
Do you have example log for me to test it?

**Comment by JonasToedter** [comment]
Hello @LiorBanai, that is some good response time!

This example log should highlight the issue: [empty_dictionary_key.log](https://github.com/Analogy-LogViewer/Analogy.LogViewer.Serilog/files/10559149/empty_dictionary_key.log)
`{"@t":"2023-02-01T13:13:36.4644801Z","@mt":"A dictionary: @{dict}","dict":{"FirstKey":"FirstItem","SecondKey":"SecondItem","":"","FourthKey":"FourthItem"}}
`

![image](https://user-images.githubusercontent.com/87964204/216101383-dc6c6e41-4ffc-4c9a-88e9-03af5446c149.png)

**Comment by LiorBanai** [comment]
@JonasToedter Thanks! I'll check this later this week. This shouldn't be hard to fix

**Comment by LiorBanai** [comment]
Since AnalogyLogMessage class has RawText field modifying the key to something like "<empty key>" is acceptable solution.

**Comment by JonasToedter** [comment]
Thank you for the quick fix! It is working fine now on my end.

**Comment by LiorBanai** [comment]
@JonasToedter glad to know. I'll release new version next week that has this fix as part of Analogy itself with additional column that shows the raw line that was  read.
