### ISSUE TITLE
Unable to show log files with only already rendered messages

### ISSUE THREAD

**Issue by cn-byn** [Analogy-LogViewer/Analogy.LogViewer.Serilog#667]
The Serilog Compact JSON format can contain either a message template (key `@mt`) or a rendered message (key `@m`).

However, Analogy seems to show the logs only if at least one `@mt` key is present in the whole log file. Then, all the log entries are shown correctly, no matter if `@mt` or `@m` is used in the other log entries.

Example log file 1:
```json
{"@t":"2024-01-18T14:15:47.2174246Z","@m":"test","@l":"Debug"}
{"@t":"2024-01-18T14:15:47.2274198Z","@m":"test 2","@l":"Debug"}
```

Result: Does not show anything in Analogy.

Example log file 2:
```json
{"@t":"2024-01-18T14:15:47.2174246Z","@mt":"test","@l":"Debug"}
{"@t":"2024-01-18T14:15:47.2274198Z","@m":"test 2","@l":"Debug"}
```

Result: Does show both entries in Analogy correctly.

The only difference between both examples is the `@mt` instead of `@m` in the first line.

**Comment by LiorBanai** [comment]
@cn-byn Thanks for reporting this. A fix should be easy to implement.
