### ISSUE TITLE
Parse additional properties in the Json files (Process, Host/Machine name, etc..)

### ISSUE THREAD

**Issue by LiorBanai** [Analogy-LogViewer/Analogy.LogViewer.Serilog#7]

**Comment by Numpsy** [comment]
Hi,

I tried viewing some Serilog clef format log files with the log viewer, and thought it would be useful to display the SourceContext property in the Source column, so I had a look at wiring that up.
As I had some logs that contained ThreadId properties added by serilog.enrichers.thread, I thought i'd try reading that as well.

There is a test change at https://github.com/Numpsy/Analogy.LogViewer.Serilog/commit/65edc96930c937d6469ae21a01e9eb35eb13db80 if you're interested in the idea? (not sure if they are reasonable properties to be using, or if it's the right approach to get the numerical thread id from the log properties.)

**Comment by Numpsy** [comment]
On a related note, is there any means of getting all of the properties stored in the event and viewing them somehow, or is it just the ones known ones, or ones that come out via the message template that are viewable?

**Comment by LiorBanai** [comment]
> Hi,
> 
> I tried viewing some Serilog clef format log files with the log viewer, and thought it would be useful to display the SourceContext property in the Source column, so I had a look at wiring that up.
> As I had some logs that contained ThreadId properties added by serilog.enrichers.thread, I thought i'd try reading that as well.
> 
> There is a test change at [Numpsy@65edc96](https://github.com/Numpsy/Analogy.LogViewer.Serilog/commit/65edc96930c937d6469ae21a01e9eb35eb13db80) if you're interested in the idea? (not sure if they are reasonable properties to be using, or if it's the right approach to get the numerical thread id from the log properties.)

Thanks. This seems good but I don't have a CLEF file to test it on it with Thread Id with value.
Would you like to add a small test log file and unit test in the unit test project and submit a PR? (or if you wish give me example and I will write it.)



> On a related note, is there any means of getting all of the properties stored in the event and viewing them somehow, or is it just the ones known ones, or ones that come out via the message template that are viewable?

one option is just to iterate over all of them and just add the to the Text properties without  parsing.
In this way all the information will be at least visible without the parsing per property..

**Comment by LiorBanai** [comment]
> 
> 
> Ok, i'll have a look at doing something later or tommorow.
> Should that be done for just the ClefParser, or the JsonParser as well? (looks like the `testJson.clef` file used by the json parser unit test already contains `SourceContext` properties that could be tested with) ?


The ClefParser is enough. I plan to rewrite the JsonParser anyway :)

> 
> With regards to the properties, I was wondering seperately if it would be useful for the message template used to create the message text (via AnalogySink) to be user configurable rather than set to `{Message}{NewLine}{Exception}`, and if you did that it could specify any extra properties, or possibly event just add `{Properties}` to the output to get them all?

Actually this is better idea then just dumping those in the Text property.

**Comment by Numpsy** [comment]
Sent.

There is actually a [Serilog.Enrichers.Process](https://github.com/serilog/serilog-enrichers-process) that can add a ProcessId property to the log entries, so you could possibly try to read that in the same way as the ThreadIds ?

**Comment by LiorBanai** [comment]
Thanks, I'll check it!
